export const palette = {
  black: '#000000',
  blueBright: '#6638FF',
  blueDarkest: '#393642',
  blueDark: '#413E4E',
  blueText: '#6B6A80',
  blueOcean: '#0069f9',
  blueLight: '#00EBE5',
  blueBorder: '#6B6A80',
  grayBackground: '#F7F7F7',
  grayBackgroundLight: '#E0E0E0',
  borderGray: '#E8E8E8',
  grayMostDark: '#666666',
  grayDark: '#AFAFB7',
  grayLessDark: '#B3B1B8',
  grayMediumDark: '#9A9A9A',
  grayMedium: '#03C4BF',
  grayMediumLight: '#D1D1D1',
  grayLight: '#00EBE5',
  green: '#00AC3D',
  lightGreen: '#37EB77',
  red: '#FF0000',
  redDark: '#FF5050',
  transparent: 'transparent',
  white: '#FFFFFF',
};

export const colors = {
  backgroundGray: palette.grayBackground,
  backgroundLightGray: palette.grayBackgroundLight,
  backgroundBlue: palette.blueDark,
  brightBlue: palette.blueBright,
  black: palette.black,
  blue: palette.blueLight,
  blueOcean: palette.blueOcean,
  blueText: palette.blueText,
  borderGray: palette.borderGray,
  borderBlue: palette.blueBorder,
  buttonPrimaryBackground: palette.grayLight,
  buttonPrimaryBorder: palette.grayLight,
  buttonSecondaryBackground: palette.white,
  buttonSecondaryBorder: palette.grayDark,
  buttonDarkBackground: palette.grayDark,
  grayBackground: palette.grayBackground,
  grayText: palette.grayDark,
  settingsGray: palette.grayMedium,
  settingsGrayDark: palette.grayMostDark,
  settingsGrayChevron: palette.grayLessDark,
  green: palette.green,
  lightGreen: palette.lightGreen,
  red: palette.red,
  invalid: palette.redDark,
  transparent: palette.transparent,
  white: palette.white,
  underlineGray: palette.grayMediumLight,
  spendableBalance: palette.blueDarkest,
  darkGrayText: palette.grayMediumDark,
};

export type ColorTypes = keyof typeof colors;
