export const palette = {
  black: '#000000',
  blueDark: '#413E4E',
  blueLight: '#00EBE5',
  blueText: '#6B6A80',
  borderGray: '#E8E8E8',
  grayDark: '#AFAFB7',
  grayLight: '#00EBE5',
  green: '#00AC3D',
  red: '#FF0000',
  transparent: 'transparent',
  white: '#FFFFFF',
};

export const colors = {
  backgroundBlue: palette.blueDark,
  black: palette.black,
  blue: palette.blueLight,
  blueText: palette.blueText,
  borderGray: palette.borderGray,
  buttonPrimaryBackground: palette.grayLight,
  buttonPrimaryBorder: palette.grayLight,
  buttonSecondaryBackground: palette.white,
  buttonSecondaryBorder: palette.grayDark,
  grayText: palette.grayDark,
  green: palette.green,
  red: palette.red,
  transparent: palette.transparent,
  white: palette.white,
};
