export const customIcons = {
  'arrow-max': require('./arrow-max').default,
  'check-circle': require('./check-circle').default,
  'face-id': require('./face-id').default,
  'info-border': require('./info-border').default,
  'more-circle': require('./more-circle').default,
  'qr-code': require('./qr-code').default,
  'question-square': require('./question-square').default,
  'refresh-2': require('./refresh-2').default,
  'prepaid-card': require('./prepaid-card').default,
  'user-check-square': require('./user-check-square').default,
  'phone-pc': require('./phone-pc').default,
  'user-with-background': require('./user').default,
  info: require('./info').default,
  split: require('./split').default,
  cardstack: require('./cardstack').default,
  circle: require('./circle').default,
  cloud: require('./cloud').default,
  discord: require('./discord').default,
  doubleCaret: require('./doubleCaret').default,
  inventory: require('./inventory').default,
  error: require('./error').default,
  more: require('./more').default,
  pay: require('./pay').default,
  refresh: require('./refresh').default,
  reload: require('./reload').default,
  send: require('./send').default,
  success: require('./success').default,
  swap: require('./swap').default,
  thumbprint: require('./thumbprint').default,
  warning: require('./warning').default,
  crosshair: require('./crosshair').default,
  mandello: require('./mandello').default,
  spend: require('./spend').default,
  wallet: require('./wallet').default,
  'camera-icon': require('./camera').default,
  'pay-icon': require('./pay-icon').default,
  'connect-icon': require('./connect-icon').default,
  share: require('./share').default,
  walletConnect: require('./walletconnect').default,
  rewards: require('./rewards').default,
  house: require('./house').default,
  'chevron-left-no-box': require('./chevron-left-no-box').default,
  offline: require('./offline').default,
};

export type CustomIconNames = keyof typeof customIcons;
