platform :ios, '11.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Prevent Cocoapods from collecting stats, which adds time to each pod installation
ENV['COCOAPODS_DISABLE_STATS'] = 'true'


target 'Rainbow' do
  # Pods for Rainbow
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Rainbow's Internal Modules.
  pod 'Rainbow-Internals', :path => './Internals'

  pod 'FLAnimatedImage'
  pod 'libwebp'
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  pod "PanModal", :git => 'https://github.com/osdnk/PanModal', :commit => '67557e18491ddfd2e2d1af0f36efb8f0202589f7'

  pod 'Shimmer'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  if ENV['SKIP_FLIPPER'] != "true"
    use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
  end
    post_install do |installer|
      react_native_post_install(installer)
  end
end
