default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    read_fastlane_session
  end

  ########################################################################
  # Adhoc Lane
  ########################################################################
  desc "Ad-hoc build"
  lane :adhoc do |options|
    ########################
    # Set Xcode Version
    ########################
    xcversion(version: "10.1")
    
    ########################
    # Pull certs & profiles
    ########################
    sync_code_signing(type: "appstore")
    sync_code_signing(type: "adhoc", force_for_new_devices: true)

    ########################
    # Build the app
    ########################
    increment_build_number(build_number: options[:build_number])

    # Make sure and set either GYM_WORKSPACE or GYM_PROJECT and GYM_SCHEME
    build_ios_app(
      export_method: "ad-hoc",
      include_bitcode: true
    )

    ########################
    # Upload to App Center
    ########################
    distribute = options[:distribute].to_s != 'false'


    if distribute
      appcenter_upload(
        ipa: "./#{ENV['GYM_OUTPUT_NAME']}.ipa",
        dsym: "./#{ENV['GYM_OUTPUT_NAME']}.app.dSYM.zip"
      )

      if ENV['SLACK_URL']
        group = ENV['APPCENTER_DISTRIBUTE_GROUP'] || 'Collaborators'
        # slack(message: "Successfully distributed *iOS* build *#{options[:build_number]}* to the *#{group}* group on App Center")
      end
    end
  end

  ########################################################################
  # Beta Lane
  ########################################################################
  desc "Beta build"
  lane :beta do |options|
    ########################
    # Set Xcode Version
    ########################
    xcversion(version: "10.1")

    ########################
    # Pull certs & profiles
    ########################
    sync_code_signing(type: "appstore")

    ########################
    # Build the app
    ########################
    increment_build_number(build_number: options[:build_number])

    # Make sure and set either GYM_WORKSPACE or GYM_PROJECT and GYM_SCHEME
    build_ios_app(
      export_method: "app-store",
      include_bitcode: true
    )

    ########################
    # Upload to TestFlight
    ########################
    upload_to_testflight
  end

  desc "Production build"
  lane :production do |options|
    ########################
    # Set Xcode Version
    ########################
    xcversion(version: "10.1")
    
    ########################
    # Pull certs & profiles
    ########################
    sync_code_signing(type: "appstore")

    ########################
    # Build the app
    ########################
    increment_build_number(build_number: options[:build_number])

    # Make sure and set either GYM_WORKSPACE or GYM_PROJECT and GYM_SCHEME
    build_ios_app(
      export_method: "app-store",
      include_bitcode: true
    )

    ########################
    # Upload to AppStore Connect
    ########################
    upload_to_app_store(
      force: true,
      submit_for_review: false,
      automatic_release: false
    )
  end

  error do |lane, exception|
    if ENV['SLACK_URL']
      # slack(
      #   message: exception.message,
      #   success: false
      # )
    end
  end
end