
default_platform(:ios)

platform :ios do
  before_all do |options|
    setup_ci
  end

  ########################################################################
  # Alpha Lane
  ########################################################################
  desc "Alpha build"
  lane :alpha do |options|
    decrypt_app_vars(
      namespace: 'alpha'
    )

    ########################
    # Pull certs & profiles
    ########################
    sync_code_signing(type: "appstore")

    ########################
    # Increment the build number
    ########################
    increment_build_number(build_number: options[:build_number])

    ########################
    # Build the app
    ########################
    build_ios_app(
      export_method: "app-store",
      include_bitcode: false,
      skip_profile_detection: true,
      scheme: "Rainbow",
      configuration: "Release"
    )

    # As build was successful, set an appropriate git tag
    set_git_tag(build_number: options[:build_number])

    # Push new tag
    push_to_git_remote()
  end

  ########################################################################
  # Beta Lane
  ########################################################################
  desc "Beta build"
  lane :beta do |options| 
    decrypt_app_vars(
      namespace: 'beta'
    )

    ########################
    # Pull certs & profiles
    ########################
    sync_code_signing(type: "appstore")

    ########################
    # Increment the build number
    ########################
    increment_build_number(build_number: options[:build_number])

    ########################
    # Build the app
    ########################
    build_ios_app(
      export_method: "app-store",
      include_bitcode: false,
      skip_profile_detection: true,
      scheme: "Rainbow",
      configuration: "Release"
    )

    ########################
    # Upload to TestFlight
    ########################
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: "1549183378",
      username: "hassan@cardstack.com",
      team_id: "QS5AFH4668"
    )

    # As build was successful, set an appropriate git tag
    set_git_tag(build_number: options[:build_number])

    # Push new tag
    push_to_git_remote()
  end

  ########################################################################
  # Production Lane
  ########################################################################
  desc "Production build"
  lane :production do |options|
    
    decrypt_app_vars(
      namespace: 'release'
    )

    ########################
    # Pull certs & profiles
    ########################
    sync_code_signing(type: "appstore")

    ########################
    # Build the app
    ########################
    increment_build_number(build_number: options[:build_number])

    build_ios_app(
      export_method: "app-store",
      include_bitcode: false
    )

    ########################
    # Upload to TestFlight
    ########################
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
      apple_id: "1549183378",
      username: "hassan@cardstack.com",
      team_id: "QS5AFH4668"
    )

    # As build was successful, set an appropriate git tag
    set_git_tag(build_number: options[:build_number])

    # Push new tag
    push_to_git_remote()
  end

  desc "Version bump"
  lane :version_bump do |options|
    if ['major', 'minor', 'patch'].include?(ENV['VERSION_CHANGE_TYPE'])
      increment_version_number_in_xcodeproj(
        bump_type: ENV['VERSION_CHANGE_TYPE'],
        target: 'Rainbow'
      )

      version = get_version_number_from_xcodeproj( target: 'Rainbow' )
      p "iOS version updated to " + version
    end
  end

  desc "Set Git Tag"
  lane :set_git_tag do |options|
    version = get_version_number_from_xcodeproj()

    # Create a local tag with the new version
    add_git_tag(
      tag: "v#{version}-ios-#{options[:build_number]}",
      prefix: "v",
      build_number: version
    )
  end
end