declare module 'react-native-dotenv' {
  export const GANACHE_URL: string;
  export const IMGIX_DOMAIN: string;
  export const IMGIX_TOKEN: string;
  export const ENABLE_PAYMENTS: string;
  export const INFURA_PROJECT_ID: string;
  export const INFURA_PROJECT_ID_DEV: string;
  export const CRYPTOCOMPARE_API_KEY: string;
  export const MERCHANT_ID: string;
  export const MERCHANT_ID_TEST: string;
  export const RAINBOW_MASTER_KEY: string;
  export const WYRE_ACCOUNT_ID: string;
  export const WYRE_ACCOUNT_ID_TEST: string;
  export const WYRE_API_KEY: string;
  export const WYRE_API_KEY_TEST: string;
  export const WYRE_ENDPOINT: string;
  export const WYRE_ENDPOINT_TEST: string;
  export const WYRE_SECRET_KEY: string;
  export const WYRE_SECRET_KEY_TEST: string;
  export const FIXER_API_KEY: string;
}
