declare module 'react-native-dotenv' {
  export const GANACHE_URL: string;
  export const IMGIX_DOMAIN: string;
  export const IMGIX_TOKEN: string;
  export const CRYPTOCOMPARE_API_KEY: string;
  export const MERCHANT_ID: string;
  export const MERCHANT_ID_TEST: string;
  export const CARDWALLET_MASTER_KEY: string;
  export const WYRE_ACCOUNT_ID: string;
  export const WYRE_ACCOUNT_ID_TEST: string;
  export const WYRE_API_KEY: string;
  export const WYRE_API_KEY_TEST: string;
  export const WYRE_ENDPOINT: string;
  export const WYRE_ENDPOINT_TEST: string;
  export const WYRE_SECRET_KEY: string;
  export const WYRE_SECRET_KEY_TEST: string;
  export const HUB_URL: string;
  export const HUB_URL_STAGING: string;
  export const STATUS_API_BASE_URL: string;
  export const VERSION_TAP_COUNT: string;
  export const OPENSEA_API_KEY: string;
  export const SECURE_STORE_KEY: string;
  export const SENTRY_ENDPOINT: string;
  export const WALLET_CONNECT_PROJECT_ID: string;
}
