name: iOS e2e

on:
  push:
    branches-ignore:
      - develop

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30

    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.5

    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Rebuild detox
      if: steps.cache.outputs.cache-hit == 'true'
      run: yarn detox clean-framework-cache && yarn detox build-framework-cache

    - name: Install dependencies
      run: |
        yarn install --network-timeout 300000 --network-concurrency 1
    
    - name: Apply patches
      run: |
        yarn patch-package

    - name: Cache Pods
      uses: actions/cache@v1
      id: podcache
      with:
        path: ios/Pods
        key: pods-${{ hashFiles('**/Podfile.lock') }}

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        cd ios && pod install && cd ..
    - run: brew tap wix/brew
    - run: brew install applesimutils
    - run: yarn e2e:smoke:ios