name: PR Verify

on:
  push:
    branches-ignore:
      - develop

jobs:
  check:
    outputs:
      run_verify: ${{ steps.check_files.outputs.run_verify }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Check if modified files are in cardstack directory
        id: check_files
        run: |
          echo "======== list modified files ========"
          git diff --name-only HEAD origin/develop

          echo "======== check paths of modified files ========"
          git diff --name-only HEAD origin/develop > files.txt
          while IFS= read -r file
          do
            echo $file
            if [[ $file = cardstack/* ]]; then
              echo "This modified file is under the 'cardstack' folder."
              echo "::set-output name=run_verify::true"
              break
            else
              echo "::set-output name=run_verify::false"
            fi
          done < files.txt

  verify:
    runs-on: ubuntu-latest
    if: needs.check.outputs.run_verify == 'true'
    needs: check

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - name: Set up yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --network-timeout 300000 --network-concurrency 1
      - name: Apply patches
        run: |
          yarn patch-package
      - name: Run lint
        run: |
          yarn lint
      - name: Check TS
        run: |
          yarn ts-check
      - name: Run Tests
        run: |
          yarn test
