name: PR Verify

on:
  push:
    branches-ignore:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: PR Verify
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.5

    - name: Lint and test
      run: |
        yarn
        yarn lint
        yarn test