name: PR Verify

on:
  push:
    branches-ignore:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.5
    - name: Install dependencies
      run: |
        yarn install --network-timeout 300000 --network-concurrency 1
    - name: Allow scripts
      run: |
        yarn allow-scripts
    - name: Create .env file
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: ".env"
        FILE_DATA: ""
    - name: Post install
      run: |
        yarn postinstall
    - run: |
        yarn lint