name: PR Verify

on:
  push:
    branches-ignore:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@master
    - uses: c-hive/gha-yarn-cache@v1
    - name: Lint and test
      run: |
        yarn setup
        yarn lint
        yarn test