name: PR Verify

on:
  push:
    branches-ignore:
      - develop
      - ci-setup

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.5
    - name: Install dependencies
      run: |
        yarn install --network-timeout 300000 --network-concurrency 1
    - name: Apply patches
      run: |
        yarn patch-package
    - name: Run lint
      run: |
        yarn lint
    - name: Check TS
      run: |
        yarn ts-check