name: PR Verify

on:
  push:
    branches-ignore:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.15.5
    - name: Lint and test
      run: |
        yarn setup
        yarn lint
        yarn test