name: PR Verify

on:
  push:
    branches-ignore:
      - develop

jobs:
  check:
    outputs:
      run_verify: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

  verify:
    runs-on: ubuntu-latest
    if: needs.check.outputs.run_verify == 'true'
    needs: check

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - name: Set up yarn cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install --network-timeout 300000 --network-concurrency 1
      - name: Apply patches
        run: |
          yarn patch-package
      - name: Run lint
        run: |
          yarn lint
      - name: Check TS
        run: |
          yarn ts-check
      - name: Run Tests
        run: |
          yarn test
