name: Release Android
on:
  workflow_dispatch:
    inputs:
      githubRef:
        description: 'Github ref to build and release'
        required: true
        default: 'develop'
  release:
    types: [created]

jobs:
  release-android:
    name: Release Android
    runs-on: macos-latest
    env:
      CRYPTEX_GIT_URL: https://${{ secrets.CI_GITHUB_PERSONAL_ACCESS_TOKEN }}@github.com/${{ secrets.CRYPTEX_GIT_REPOSITORY }}.git
      CRYPTEX_PASSWORD: ${{ secrets.CRYPTEX_PASSWORD }}
    steps:
      - name: Set environment variables
        env:
          DEFAULT_REF: ${{ github.event.release.tag_name }}
        run: |
          echo "CHECKOUT_REF=${{ github.event.inputs.githubRef || env.DEFAULT_REF }}" >> $GITHUB_ENV
      - uses: sarisia/actions-status-discord@v1
        if: ${{ always() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: Android release started
          color: 0xFFFFFF
      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CHECKOUT_REF }}
      - uses: volta-cli/action@v4
      - name: Setup Ruby & bundle
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Decrypt fastlane vars
        run: yarn fastlane run decrypt_fastlane_vars
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'yarn'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Yarn Install
        run: yarn install --prefer-offline --frozen --frozen-lockfile
      - name: Yarn Setup
        run: yarn postinstall
      - name: Sync google_services
        run: yarn contexts:sync:google_services
      - name: Sync app_vars
        run: yarn contexts:app:sync
      - name: Sync google_play_credentials
        run: yarn fastlane sync_google_play_credentials
      - name: Sync android_keystore
        run: yarn fastlane sync_android_keystore
      - name: Sync sentry_properties
        run: yarn fastlane sync_sentry_properties
      - name: Run fastlane (android)
        run: cd android && bundle install && bash -c 'set -a && source ../.env && set +a && bundle exec fastlane internal'
      - uses: actions/upload-artifact@v3
        with:
          name: Android bundle
          path: android/app/build/outputs/bundle/app-release.aab
      - uses: sarisia/actions-status-discord@v1
        if: ${{ failure() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: Android release failed
          color: 0xFF5054
      - uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: Android release completed
          color: 0x37EB77
